version: '3.8'

services:
  vida_livre:
    container_name: vida_livre
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
